// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright 2026 Bogdan Shapovalov and the Fury authors

//! Bakes `shared/personas/contributed/*.json` into the crate.
//!
//! The two base personas are `include_str!`'d by name in catalogue.rs. Contributed
//! ones arrive by pull request, one file each, and naming each in source would
//! make every contribution a two-file change that a contributor has to get
//! right. So this walks the directory at build time and writes one generated
//! array of `(file name, contents)`; catalogue.rs parses them at runtime and
//! appends what parses. A file that does not parse is a build failure here,
//! not a silent absence — the CI check on the pull request runs the same
//! parse, so it should never get this far.

use std::path::Path;

fn main() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../shared/personas/contributed");
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut entries: Vec<String> = Vec::new();
    if let Ok(read) = std::fs::read_dir(&dir) {
        let mut files: Vec<_> = read
            .flatten()
            .map(|e| e.path())
            .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("json"))
            .collect();
        files.sort();
        for f in files {
            println!("cargo:rerun-if-changed={}", f.display());
            let text = std::fs::read_to_string(&f).expect("contributed persona is readable");
            // Fail the build on a file that is not JSON at all; the shape is
            // checked at runtime where Persona lives.
            serde_json::from_str::<serde_json::Value>(&text)
                .unwrap_or_else(|e| panic!("{} is not JSON: {e}", f.display()));
            let name = f.file_name().unwrap().to_string_lossy().to_string();
            entries.push(format!(
                "    ({:?}, include_str!({:?})),",
                name,
                f.canonicalize().unwrap().display().to_string()
            ));
        }
    }

    let out = Path::new(&std::env::var("OUT_DIR").unwrap()).join("contributed_personas.rs");
    std::fs::write(
        &out,
        format!(
            "/// Generated by build.rs from shared/personas/contributed/.\npub const CONTRIBUTED: &[(&str, &str)] = &[\n{}\n];\n",
            entries.join("\n")
        ),
    )
    .unwrap();
}
